--insert into USERS (EMAIL, FIRST_NAME, LAST_NAME) values ('me@you.com', 'Joe', 'Schmoe');
--insert into USERS (EMAIL, FIRST_NAME, LAST_NAME) values ('deltron@te.com', 'Billy', 'Toms');
--
--insert into FAVORITES (USER_ID, ITEM_ID) values (1, 12345);
--insert into FAVORITES (USER_ID, ITEM_ID) values (1, 56789);
--insert into FAVORITES (USER_ID, ITEM_ID) values (2, 54321);
--insert into FAVORITES (USER_ID, ITEM_ID) values (2, 98765);